### ISSUE TITLE
config.auth.connectionRequest could take a callback

### ISSUE THREAD

**Issue by rplatel** [genieacs/genieacs#129]
config.auth.connectionRequest in config/auth.js takes a deviceId and wants the connection Request username and password returned.  

The way we're thinking of deploying, we may need to make one or more HTTP requests to get the connection request credentials for a deviceId.

It would be nice if config.auth.connectionRequest took a callback argument to allow this kind of use case.

**Comment by zaidka** [comment]
I think your suggestion can be implemented in a backward compatible way by checking if the return value is not null/undefined then use that as the credentials, otherwise wait for the callback function to be called. With such implementation that doesn't break existing configurations of users, we can include it in the next maintenance release. Pull requests are welcome.

**Comment by DrumSergio** [comment]
Any news on this topic?

**Comment by rplatel** [comment]
Bump

**Comment by zaidka** [comment]
It's implemented. See config/auth-sample.js.
