### ISSUE TITLE
Task execution is not aborted when a task is deleted

### ISSUE THREAD

**Issue by okraits** [genieacs/genieacs#263]
Version of GenieACS: latest git.

### What I did:

1. I created a refreshObject task via the REST-API for the whole tree ('InternetGatewayDevice') and waited for the task to be executed.
2. When the task was running, I deleted the task by clicking on the *Destroy* link in the task queue.

### What I saw:

* GenieACS and the device continued executing that task.
* Further tasks were not executed although they were at the top of the task queue.

### What I expected instead:

* Task execution should be aborted when a task is deleted
* Following tasks in the queue should be immediately executed after the current task is deleted

**Comment by zaidka** [comment]
> GenieACS and the device continued executing that task.

This is the expected behavior. It's not possible to cancel a task while it's being processed.

> Further tasks were not executed although they were at the top of the task queue.

If the tasks were added after the session has already started, then this is also the expected behavior. The tasks are fetched at the beginning of the session so anything added after that will be executed in the next session.

**Comment by okraits** [comment]
Ok, so I'll close this now.
