### ISSUE TITLE
"Invalid Session" with nginx and keep-alives 

### ISSUE THREAD

**Issue by rplatel** [genieacs/genieacs#281]
We have nginx in front of genieacs-cwmp to handle HTTP auth of CPEs and do some ACL enforcement.

With keep-alives turned on in nginx CPEs will get partway through an INFORM conversation then get a 400 Bad Request with the body "Invalid Session" from genieacs.

What's happening is that nginx is keeping sockets between itself and cwmp open and passing different clients' HTTP requests over those sockets.  (I've seen this comparing tcpdumps between the CPEs and nginx and nginx and genieacs-cwmp)  So in cwmp.coffee:getSession() the sessionId provided by the client cookie does not match the sessionId associated with that socket.

I believe this is a bug since genieacs-cwmp is trying to keep client state between HTTP requests which is a no-no.

Turning keepalives off in nginx fixes the problem but is not ideal.

I'm not expert enough at coffeescript to suggest a patch, but perhaps if currentSessions was a Map instead of a WeakMap, getSessions could iterate through it and see if the sessionId presented by the client is valid in another session and steal that session.

**Comment by zaidka** [comment]
This is intentional. Genie assumes one session per TCP connection in order be able to store the session state in memory. Without this assumption we'll have to store the session state in the database which will result in a significant performance hit. nginx is reusing a pool of upstream TCP connections and because of that requests belonging to a single TR-069 session can end up in different processes or even servers.

If you can configure nginx to have one to one mappings of upstream and downstream TCP connections then that should solve the problem. Let me know if you manage to do that or have other ideas.
