### ISSUE TITLE
API get Presets error

### ISSUE THREAD

**Issue by ppkamp** [genieacs/genieacs#299]
Hi,

I have lots of presets with the same ID as the device ID (I can see them in the GUI).
When I try to list all of them I get only two, and if I ask only for a specific Preset I get nothing (unless I ask for one of the two presets listed before, so the API call is correct).

Any ideas to solve the problem?

**Comment by akcoder** [comment]
This is a really bad idea and causes performance issues because for each device inform/boot/etc genie has to spin through all the presets figuring out which ones match and then apply them.

A much better way of accomplishing what you are trying to do is documented on the wiki under the article titles “example of a provisioning workflow”

-dan

**Comment by ppkamp** [comment]
Ok, I understand.
I have just read that article but I have not clear how to get the device parameters stored in our web app to the provisioning script... 

Anyway, It seems that if you have more than X presets, the API call to get all of them or a specific one fails.

**Comment by akcoder** [comment]
Re-read the wiki entry. Everything is there. 

-dan
